public virtual without sharing class TriggerHandler {

    public virtual void beforeInsert(TriggerContext context) {}

    public virtual void afterInsert(TriggerContext context) {}

    public virtual void beforeUpdate(TriggerContext context) {}

    public virtual void afterUpdate(TriggerContext context) {}

    public virtual void beforeDelete(TriggerContext context) {}

    public virtual void afterDelete(TriggerContext context) {}

}